import turtle
wn=turtle.Screen()
wn.bgpic("road.gif")
t=turtle.Turtle()
t.begin_fill()

t.penup()
t.back(250)
t.pendown()
t.speed(10)
t.color("blue")
t.pensize(5)
for i in range(2):
    t.fd(500)
    t.rt(90)
    t.fd(45)
    t.rt(90)
t.fd(60)
t.lt(45)
t.forward(150)
t.right(45)
t.forward(200)
t.rt(50)
t.fd(143)
t.penup()
t.goto(0,105)
t.pendown()
t.rt(40)
t.fd(150)
t.hideturtle()
# t.end_fill()

wheel=turtle.Turtle()

wheel.penup()
wheel.goto(-170,-80)
wheel.pendown()
wheel.begin_fill()
for i in range(2):
    wheel.circle(30,180)
wheel.end_fill()
wheel.penup()
wheel.goto(170,-80)
wheel.pendown()
wheel.begin_fill()
for i in range(2):
    wheel.circle(30,180)
wheel.end_fill()
wheel.penup()
wheel.goto(10,30)
wheel.pendown()
for i in range(2):
    wheel.fd(15)
    wheel.rt(90)
    wheel.fd(7.5)
    wheel.rt(90)
    
